"""initial tables

Revision ID: 1b5af17758cf
Revises: 
Create Date: 2026-07-20

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b5af17758cf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)

    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legajo', sa.String(length=50), nullable=True),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('admission_date', sa.String(length=10), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_dni'), 'employees', ['dni'], unique=True)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index(op.f('ix_employees_legajo'), 'employees', ['legajo'], unique=False)

    op.create_table('timesheet_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('entry_time', sa.String(length=5), nullable=True),
    sa.Column('exit_time', sa.String(length=5), nullable=True),
    sa.Column('total_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('is_franco', sa.Boolean(), nullable=False),
    sa.Column('is_holiday', sa.Boolean(), nullable=False),
    sa.Column('holiday_name', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timesheet_records_date'), 'timesheet_records', ['date'], unique=False)
    op.create_index(op.f('ix_timesheet_records_employee_id'), 'timesheet_records', ['employee_id'], unique=False)
    op.create_index(op.f('ix_timesheet_records_id'), 'timesheet_records', ['id'], unique=False)

    op.create_table('payrolls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('basic_salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('seniority_years', sa.Integer(), nullable=False),
    sa.Column('seniority_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('presentismo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('overtime_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('overtime_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('holiday_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('holiday_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('night_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('night_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('viaticos', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('non_remunerative', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gross_salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('deductions', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sac_bruto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sac_deducciones', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sac_neto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payrolls_employee_id'), 'payrolls', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payrolls_id'), 'payrolls', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payrolls_id'), table_name='payrolls')
    op.drop_index(op.f('ix_payrolls_employee_id'), table_name='payrolls')
    op.drop_table('payrolls')
    op.drop_index(op.f('ix_timesheet_records_id'), table_name='timesheet_records')
    op.drop_index(op.f('ix_timesheet_records_employee_id'), table_name='timesheet_records')
    op.drop_index(op.f('ix_timesheet_records_date'), table_name='timesheet_records')
    op.drop_table('timesheet_records')
    op.drop_index(op.f('ix_employees_legajo'), table_name='employees')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_dni'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
